insert into category values (1, 'hip-hop');
insert into category values (2, 'rock');
insert into category values (3, 'glitch');
insert into category values (4, 'pop');
insert into category values (5, 'jazz');
insert into category values (6, 'classical');
insert into user  values (2, '1998-01-13','test@test.com','1000000000','test123','Test', 'Edit your bio!');
insert into user  values (3, '2002-12-01','test2@test.com','1000000001','test234','Test2', 'Edit your bio!');
insert into user  values (4, '2005-01-19', 'test3@test.com', '1000000002', "test345", 'Test3', 'Edit your bio!');
insert into post values (3, 'Why in the world is there 4 vinyl versions of Taylor Swifts latest LP?', 'For why',4, 2);
insert into post values (4, 'I miss the old danny brown', 'What happened?', 5, 3);
insert into post values (5, 'Beethovens 5th is such a banger. Seriously. So underrated', 'the GOAT', 6, 4);